name: portfolio_v_1_0
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.9.1
  google_fonts: ^6.3.2
  http: ^1.6.0
  path_provider: ^2.1.5
  pdfx: ^2.9.2
  permission_handler: ^12.0.1
  photo_view: ^0.15.0
  syncfusion_flutter_pdfviewer: ^31.1.19
  url_launcher: ^6.3.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/files/

